server:
  port: 20002
  tomcat:
    accesslog:
      enabled: false
    basedir: ./tomcatlog
  servlet:
    context-path: /sys
spring:
  application:
    #authentication service
    name: microsys
  datasource:
#    url: "jdbc:mysql://127.0.0.1:3333/patrol?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai"
#    username: root
#    password: 123456
#    url: "jdbc:mysql://1.192.212.229:3306/platsys?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
#    username: root
#    password: Huadao_@123
    url: "jdbc:mysql://192.168.3.78:3306/platsys?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
    username: root
    password: Huadao_@123

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
#      url: "jdbc:mysql://127.0.0.1:3333/patrol?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai"
#      username: root
#      password: 123456
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      query-timeout: 30
  data:
    mongodb:
      #      uri: mongodb://root:123456@192.168.3.78:27017/gatewaylogs?authSource=admin&authMechanism=SCRAM-SHA-1
      uri: mongodb://localhost:27017/syslogs
  redis:
    port: 6379
    host: localhost
    password:
    jedis:
      pool:
        max-active: 8
    database: 0
    timeout: 5000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type:  correlated
    publisher-returns: true
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        max-concurrency: 5
        concurrency: 1
        retry:
          enabled: true
          # 最大重试次数
          max-attempts: 5
          # 重试间隔时间(毫秒)
          initial-interval: 3000
        prefetch: 1     #每次检索到缓存队列消息数目，手动反馈的建议1；否则，越大速度越快
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.hd.microsysservice.entity
  global-config:
    worker-id:    1
    datacenter-id:  3
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    root: error
    com.hd: debug
    com.alibaba: error
    org.apache.tomcat: error
    org.apache.catalina: error
config:
  scanUri: false
  USER_OP_IDENTIFICATION: "SFSDF-332-DFDGSG-323-EG-SDG$rfy*kjg"
  attach-path: D:/tmp123/attach/
#  heart-beat-uri: http://127.0.0.1:20003/monitor/heartbeat
  heart-beat-uri: http://192.168.3.78:20003/monitor/heartbeat