server:
  port: 10001
spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/auserverlogs
  datasource:
    url: "jdbc:mysql://127.0.0.1:3333/patrol?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456

#    url: "jdbc:mysql://1.192.212.229:3306/user-center?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
#    url: "jdbc:mysql://192.168.3.78:3306/user-center?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
#    username: root
#    password: Huadao_@123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.hd.auserver.entity
  global-config:
    worker-id:    1
    datacenter-id:  1
logging:
  level:
    root: error
    com.hd: debug
config:
  USER_OP_IDENTIFICATION: "SFSDF-332-DFDGSG-323-EG-SDG$rfy*kjg"
  RSA_FILE_PATH:  "d:/tmp123/"
