server:
  port: 10001
spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/logs
logging:
  level:
    com: info
    org: info
    org.springframework.security: debug
