server:
  port: 9001
spring:
  application:
    name: gateway
  profiles:
    active: online
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: test
      uri: mongodb://localhost:27017/gatewaylogs
logging:
  level:
    root: error
    com.hd: debug
    com.alibaba: error
    sun.net: error
