server:
  port: 20001
spring:
  application:
    name: gateway
  profiles:
    active: online
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: test
      uri: mongodb://localhost:27017/gatewaylogs
logging:
  level:
    root: error
    com.hd: debug
    com.alibaba: error
    sun.net: error
config:
  auth-uri: 127.0.0.1:20002  #访问授权检查的uri
  session-timeout: 20   #minutes
  check-permission: true       #是否检查权限