server:
  port: 20001
spring:
  application:
    name: gateway
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: test
      uri: mongodb://localhost:27017/gatewaylogs
logging:
  level:
    root: debug
    com.hd: debug
    com.alibaba: error
    sun.net: error
config:
  auth-uri: 127.0.0.1:20002  #访问授权检查的uri
  session-timeout: 200   #minutes
  check-token: true       #是否检查令牌
  check-permission: true       #是否检查权限
  heart-beat-uri: http://127.0.0.1:20003/monitor/heartbeat
#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'