server:
  port: 20001
spring:
  application:
    name: gateway
  data:
    mongodb:
      #      uri: mongodb://root:123456@192.168.3.78:27017/gatewaylogs?authSource=admin&authMechanism=SCRAM-SHA-1
      uri: mongodb://127.0.0.1:27017/gatewaylogs
  redis:
    port: 6379
    host: localhost
    password:
    jedis:
      pool:
        max-active: 8
    database: 0
    timeout: 5000

logging:
  level:
    root: error
    com.hd: debug
    com.alibaba: error
    sun.net: error
config:
  ip-token-capacity: 1000
  ip-token-refill:  20
  service-token-capacity: 2000
  service-token-refill:  50
  session-timeout: 120   #minutes
  check-token: true       #是否检查令牌
  check-permission: true       #是否检查权限
  heart-beat-uri: http://127.0.0.1:20003/monitor/heartbeat
  microServices:
    auserver: lb://auserver,/auserver/**,2000,fallbackcmd
    micromonitor: lb://micromonitor,/micromonitor/**,2000,fallbackcmd
    microsys: lb://microsys,/microsys/**,5000,fallbackcmd
    microattach: lb://microsys,/microattach/**,30000,fallbackcmd60s
    basicconfig: lb://basicconfig,/basicconfig/**,20000,fallbackcmd60s
    execute: lb://execute,/execute/**,20000,fallbackcmd60s
    reportnews: lb://reportnews,/reportnews/**,20000,fallbackcmd60s
#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'