server:
  port: 8000
security:
  oauth2:
    resource:
    authorization:
#      jwt:
#        key-value: werwerwrwrfastboot332eww
#      prefer-token-info: true
#      token-info-uri: http://localhost:9000/oauth/check_token
#    client:
#      client-id: client
#      client-secret: secret123
#      user-authorization-uri: http://localhost:9000/oauth/authorize
#      access-token-uri: http://localhost:9000/oauth/token
logging:
  level:
    org.springframework.security: debug
